<?php $controller = ltrim(preg_replace("/([A-Z])/", " $1", 'Lớp Học'), ' ');?>

<div class="subject-title">
	<?php echo $this->text($controller) ?>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <th>Tên Lớp Học</th>                    
                    <th style="vertical-align: middle;">Chọn Lớp Học</th>
                </tr>
            </thead>

            <tbody lastest-news-content>
                <?php $grades= unserialize(CLASSES_GRADE);                	
                		if (count($grades)) : 
                    		foreach ($grades as $key => $row): ?>
    			<tr>
                       <td>
					        <?php echo $row;?>
					    </td>
					    <?php 
					    	$checked = '';
					    	if(in_array('', explode(',', '')))
					    		$checked = ' checked="checked"';
					    ?>
					    <td style="vertical-align: middle">
					    	<input type="checkbox" id="<?php echo $key; ?>" value="<?php echo $row; ?>" <?php echo $checked?>>
					    </td>
					</tr>     
                        
                <?php endforeach;else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php //echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php //echo $this->paginationControl($this->paginator, 'Sliding', 'tutors/_partial/show-tutors-pagination.phtml'); ?>
    </div>
</div>
<script>
$("input[type=checkbox]").each(function() {
	$(this).live('click', function() {
		var districts = ''; 
		if($(this).is(':checked')){
    		var data = $.trim($('#TeachableDistricts').val());
    		if($.trim(data) != '') data += ',';
        	arr =  $.unique((data+$(this).val()).split(','));
        	districts = arr.join(","); //get unique string back with
        	$('#TeachableDistricts').val(districts);        	
    	}else{
    		var data = $.trim($('#TeachableDistricts').val());
        	y =  data.split(',');
    		y.splice( $.inArray($(this).val(), y), 1 );
    		districts = y.join(","); //get unique string back with
    		$('#TeachableDistricts').val(districts);
        }
	});        
});                    
</script>