<?php
//convert object array to string for subject
function array2string($haystack, $needle){
	$str="";
	foreach($haystack as $k=>$i){
		if(is_array($i)){
			if(in_array($i['SubjectId'], $needle))
				$str.= ','.$i['SubjectName'];
			$str.=array2string($i, $needle);
		}
	}
	return $str;
}
$subjectModel = new Application_Model_Subjects();
$subjects = $subjectModel->fetchAll($subjectModel->getAllAvaiabled());
$form =  $this->form;
$class = $this->class;
?>                 <!--People Sections-->
                    <div id="people-block">
                        <h3> Ứng tuyển vị trí gia sư cho lớp học</h3>

                        <div class="row-fluid">
                            <div class="span12 people-right-block">
                            	<div class="row-fluid">	
								<?php if(! empty($this->messageStatus) && isset($this->messageStatus)): ?>
        						<?php $messageStatus = explode("/", $this->messageStatus); ?>
								<div class="span12">
								     <div class="alert alert-<?php echo $messageStatus[0];?>">
								        <button class="close" data-dismiss="alert" type="button">X</button>
								        <?php echo $messageStatus[1];?>
								        <?php if(isset($this->messages) && sizeof($this->messages) > 0): ?>
						                    <ul>
						                        <?php foreach ($this->messages as $fieldName => $message) : ?>
						                            <?php if ($this->form->$fieldName) : 
						                            		$msg = $this->form->$fieldName->getLabel();
						                            ?>
						                                <li><?php echo substr($msg, 0, -1).': '.$message; ?></li>
						                            <?php else : ?>
						                                <li><?php echo $message; ?></li>
						                            <?php endif; ?>
						                        <?php endforeach; ?>
						                    </ul>
						                <?php endif; ?>
								    </div>
								</div>
								<?php endif;?>
								</div>
                                <div class="row-fluid lastest-block">
                                    <div class="span8">
                                        <form class="form-horizontal" method="post" action="">
								            <fieldset class="well the-fieldset">
								            	<?php echo $form->ClassId; ?>
								            	<?php echo $form->TutorId; ?>
								                
								                <div class="form-actions">								                    
								            			<?php echo $this->renderFormElement($form->Save); ?>
								            			<?php echo $this->renderFormElement($form->Reset); ?>
								                </div>
								                <div>
								                	<span>Bạn chưa có mã số? Đăng ký <a href="/tutors/register"><i>tại đây</i></a></span>
								                </div>
								            </fieldset>
								        </form>
                                    </div>
                                   <div class="span4 pull-left classes featurette">
							            <fieldset class="well the-fieldset">
							            	<legend>Mã số lớp học: <?php echo $class->ClassId?></legend>
								            <div class="lastest-date1 desc-news"><span>Lớp học: </span>
								            		<?php echo $class['ClassGrade']; ?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Môn học: </span>
								            		<?php 
								            			echo ltrim(array2string($subjects->toArray(), explode(',', $class['ClassSubjects'])), ',');
								            		?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Số buổi: </span>
								            		<?php echo $class['ClassDaysOfWeek'];?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Thời gian: </span>
								            		<?php echo $class['ClassTime'];?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Yêu cầu: </span>
								            		<?php echo $class['ClassRequire'];?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Số ứng viên hiện tại: </span>
								            		<?php $tutors = explode(',', $class['ClassTutors']);?>
								            		<?php $ctutors = count($tutors);?>								            		
								            		<?php echo (isset($tutors[0]) && !empty($tutors[0])) ? $ctutors: 'Chưa có'; ?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Lương: </span>
								            		<?php echo $class['ClassCost'];?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Liên hệ: </span>
								            		<?php echo $class['ClassContact']; ?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Địa chỉ: </span>
								            		<?php echo $class['ClassAddress'];?>
								            </div>
								        </fieldset>			            
						            </div> 
                                </div>
                            </div>
                        </div>
                    </div>
