<?php if(count($this->paginator)):
    $classes = array(1,2,3,4,5,6,7,8,9,10,11,12);
?>
<!--People Sections-->
          <div id="people-block">
               <div class="row-fluid">
                <!--Lastest News Sections-->
                <div class="span12 only-popular load-more-news1">
                    <div class="row-fluid">
	                    <div class="form-actions">
				        	<div class="span12">
					        	<span>Lớp học:
					        		<select id="classes-select">
						        		<option value="">- Chọn lớp -</option>
						        		<?php foreach ($classes as $key =>$value) :?>			        			
						        			<option value="<?php echo $key+1 ?>" label="<?php echo $value; ?>"><?php echo $value; ?></option>
						        		<?php endforeach;?>
									 </select>
					        	</span>
					        	<span>&nbsp;&nbsp; &nbsp; Quận: 
						        	<select  id="districts-select">
						        		<option value="">- Chọn quận -</option>
						        		<?php foreach ($this->districts as $key =>$value) :?>			        			
						        			<option value="<?php echo $value->DistrictId ?>" label="<?php echo $value->DistrictName; ?>"><?php echo $value->DistrictName; ?></option>
						        		<?php endforeach;?>
									 </select>
						         </span>
						         <span>&nbsp; &nbsp; &nbsp; Môn học: 
					        		<select  id="subjects-select">
						        		<option value="">- Chọn môn học -</option>
						        		<?php foreach ($this->subjects as $key =>$value) :?>			        			
						        			<option value="<?php echo $value->SubjectId ?>" label="<?php echo $value->SubjectName; ?>"><?php echo $value->SubjectName; ?></option>
						        		<?php endforeach;?>
									 </select>
					        	</span>
				        	</div>
				        </div>
                        <!-- <h3 class="bottom-news">Latest News</h3> -->
                        		<?php echo $this->renderBlock('list-classes', $this)?>
                        <div id="lastest-news-content"></div>
                    </div>
                </div>
            </div>
        </div>
       </div>
<?php endif;?>                               