<?php if(count($this->paginator)):
	$tutorModel = new Application_Model_Tutors();
	$this->tutor = $tutorModel;
	$date = new Zend_Date();
?>
<!--People Sections-->
          <div id="people-block">
               <div class="row-fluid">
                <!--Lastest News Sections-->
                <div class="span12 only-popular load-more-news1">
                    <div class="row-fluid">
					<h3 class="bottom-news1">Các lớp hiện có ngày <?php echo $date->toString(DATE_FORMAT_ZEND);?></h3> 
	                    <div class="form-actions">
				        	<div class="span12">
					        	<span>Lớp học:
					        		<select id="classes-select">
						        		<option value="">- Chọn lớp -</option>
						        		<?php foreach ($this->grades as $key =>$value) :?>			        			
						        			<option value="<?php echo $value->GradeId ?>" label="<?php echo $value->GradeName; ?>"><?php echo $value->GradeName; ?></option>
						        		<?php endforeach;?>
									 </select>
					        	</span>
					        	<span>&nbsp;&nbsp; &nbsp; Quận: 
						        	<select  id="districts-select">
						        		<option value="">- Chọn quận -</option>
						        		<?php foreach ($this->districts as $key =>$value) :?>			        			
						        			<option value="<?php echo $value->DistrictId ?>" label="<?php echo $value->DistrictName; ?>"><?php echo $value->DistrictName; ?></option>
						        		<?php endforeach;?>
									 </select>
						         </span>
						         <span>&nbsp; &nbsp; &nbsp; Môn học: 
					        		<select  id="subjects-select">
						        		<option value="">- Chọn môn học -</option>
						        		<?php foreach ($this->subjects as $key =>$value) :?>			        			
						        			<option value="<?php echo $value->SubjectId ?>" label="<?php echo $value->SubjectName; ?>"><?php echo $value->SubjectName; ?></option>
						        		<?php endforeach;?>
									 </select>
					        	</span>
				        	</div>
				        </div>
                        <!-- <h3 class="bottom-news">Latest News</h3> -->
                        		<?php echo $this->renderBlock('list-classes', $this)?>
                        <div id="lastest-news-content"></div>
                    </div>
                </div>
            </div>
        </div>
<?php endif;?>                               