<?php
 $modelNews = new Application_Model_News();
 $news =  $modelNews->fetchRow($modelNews->getNewsByPrivate());
 $content = (count($news)? $news->toArray() : '');
?>                 <!--People Sections-->
                    <div id="people-block">
                        <!-- <h3> --><?php //echo (!empty($headingText['home_people'])) ? $headingText['home_people'] : ""; ?><!-- </h3> -->

                        <div class="row-fluid">
                            <div class="span12 people-right-block">
                                <div class="row-fluid">
                                    <div class="span12">
                                        <p><?php 
                                        		if (is_array($content) && count($content)) 
                                                	echo  !empty($content['Content']) ? $content['Content'] :  ' '; 
                                        		?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
