<?php
 $form =  $this->form;
 $configsModel = new Application_Model_Configs();
 $fbAcc = $configsModel->getConfigValue('account-facebook');
 $url = 'http://www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2F'.$fbAcc;
 $url .= '&height=250&colorscheme=light&show_faces=true&border_color=%23C4C4C4&stream=false&header=false';
 $style = 'border: none; overflow: hidden; width: 100%; height: 250px; background: #FFFFFF;';
?>               					
					<!--People Sections-->
                    <div id="people-block">
					<?php if(!empty($fbAcc)):?>
					<div class="exelikebox large-screen">
						<div class="slide-iframe">
							<iframe src="<?php echo $url; ?>"
							scrolling="no" frameborder="0" allowtransparency="true" 
							style="<?php echo $style; ?>"></iframe>
						</div>
					  </div>  
					   <?php endif;?>
                        <div class="row-fluid">
                            <div class="span12 people-right-block">
                            	<div class="row-fluid">	
								<?php if(! empty($this->messageStatus) && isset($this->messageStatus)): ?>
        						<?php $messageStatus = explode("/", $this->messageStatus); ?>
								<div class="span12">
								     <div class="alert alert-<?php echo $messageStatus[0];?>">
								        <button class="close" data-dismiss="alert" type="button">X</button>
								        <?php echo $messageStatus[1];?>
								        <?php if(isset($this->messages) && sizeof($this->messages) > 0): ?>
						                    <ul>
						                        <?php foreach ($this->messages as $fieldName => $message) : ?>
						                            <?php if ($this->form->$fieldName) : 
						                            		$msg = $this->form->$fieldName->getLabel();
						                            ?>
						                                <li><?php echo substr($msg, 0, -1).': '.$message; ?></li>
						                            <?php else : ?>
						                                <li><?php echo $message; ?></li>
						                            <?php endif; ?>
						                        <?php endforeach; ?>
						                    </ul>
						                <?php endif; ?>
								    </div>
								</div>
								<?php endif;?>
								</div>
                                <div class="row-fluid">
                                    <div class="span12">
                                        <form class="form-horizontal" method="post" action="" id="frmTutor">
								            <!-- <fieldset> -->
								            	<?php  echo $form->contact; ?>
								            	<?php  echo $form->level; ?>
								                <?php  echo $form->extra;?>
							                        <div class="control-group">
							                            <div class="controls">
							                              <ul id="separate-list" style="display:none" ></ul>
							                            </div>
							                          </div>
								                
								                <div class="form-actions">								                    
								            			<?php  echo $this->renderFormElement($form->Save); ?>
								            			<?php  echo $this->renderFormElement($form->Reset); ?>
								                </div>
								            <!-- </fieldset> -->
								        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>