<?php
 $modelNews = new Application_Model_News();
 $form =  $this->form;
 //$content = (count($news)? $news->toArray() : '');
?>                 <!--People Sections-->
                    <div id="people-block">
                        <!-- <h3> --><?php //echo (!empty($headingText['home_people'])) ? $headingText['home_people'] : ""; ?><!-- </h3> -->

                        <div class="row-fluid">
                            <div class="span12 people-right-block">
                            	<div class="row-fluid">	
								<?php if(! empty($this->messageStatus) && isset($this->messageStatus)): ?>
        						<?php $messageStatus = explode("/", $this->messageStatus); ?>
								<div class="span12">
								     <div class="alert alert-<?php echo $messageStatus[0];?>">
								        <button class="close" data-dismiss="alert" type="button">X</button>
								        <?php echo $messageStatus[1];?>
								        <?php if(isset($this->messages) && sizeof($this->messages) > 0): ?>
						                    <ul>
						                        <?php foreach ($this->messages as $fieldName => $message) : ?>
						                            <?php if ($this->form->$fieldName) : 
						                            		$msg = $this->form->$fieldName->getLabel();
						                            ?>
						                                <li><?php echo substr($msg, 0, -1).': '.$message; ?></li>
						                            <?php else : ?>
						                                <li><?php echo $message; ?></li>
						                            <?php endif; ?>
						                        <?php endforeach; ?>
						                    </ul>
						                <?php endif; ?>
								    </div>
								</div>
								<?php endif;?>
								</div>
                                <div class="row-fluid">
                                    <div class="span12">
                                        <form class="form-horizontal" method="post" action="">
								            <!-- <fieldset> -->
								            	<?php  echo $form->contact; ?>
								            	<?php  echo $form->level; ?>
								                <?php  echo $form->extra;?>
							                        <div class="control-group">
							                            <div class="controls">
							                              <ul id="separate-list" style="display:none"></ul>
							                            </div>
							                          </div>
								                
								                <div class="form-actions">								                    
								            			<?php  echo $this->renderFormElement($form->Save); ?>
								            			<?php  echo $this->renderFormElement($form->Reset); ?>
								                </div>
								            <!-- </fieldset> -->
								        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
<script>
$('#districts-modal').click(function(){    var url = '/districts/ajax-show-districts';
    //$('.lastest-news-content').append('<div class="loading-news"><img src="/images/preloading.gif"/><div>');
    var districts = $('#TeachableDistricts').val();
    if($.trim(districts) != '')  url += '/cdistricts/'+districts;
    loadModal('ss');
    //alert('ss');
    
   /*  $.ajax({
        url : url,
        method: 'get',
        success : function(data){
        /* 	$("#myModal").css("display","block");
          	 $("#myModal").css("top","500px");
          	$('#myModal').on('hidden', function () {
                  $(".modal-backdrop").remove();
              });
              $('#myModal').on('hide', function () {
                  $(".modal-backdrop").remove();
              });
              $(".modal-body").addClass("max-height-light-box");
              $(".modal-body").html('test');
          	$('#myModal').modal('show');
        },
        error: function (request, status, error) {
            alert(request.responseText);
        }
    }); */
});

//loadModal('ss');

</script>