<?php
    echo $this->doctype();
    $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
    $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<html>
    <head>
    <!-- The styles -->
    <link id="bs-css" href="/styles/admin/bootstrap-cerulean.css" rel="stylesheet">
    <?php //getStyleContents($this, $controller, $action, $module);
          //getScriptContents($this, $controller, $action, $module); ?>
          
          <!--<script src="<?php echo STATIC_SERVER;?>/scripts/jquery.js" type="text/javascript"></script>-->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/base/jquery-ui.css" type="text/css" media="all" />

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo STATIC_SERVER;?>/styles/main.css" rel="stylesheet" type="text/css" />
    
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="<?php echo STATIC_SERVER;?>/scripts/scripts.js" type="text/javascript"></script>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- The fav icon -->
        <link href="/images/favicon.ico" rel="SHORTCUT ICON">
    </head>

    <body data-spy="scroll">
                  <?php echo $this->layout()->content; ?>
    </body>
</html>
