<?php
 $modelNews = new Application_Model_News();
 $news =  $modelNews->fetchRow($modelNews->getNewsByPrivate());
 $content = (count($news)? $news->toArray() : '');
 $url = FRONTEND_DOMAIN_NAME.Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
?> 
			<div id="fb-root like-facebook-home"></div>
			<script>(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=642583262446502&version=v2.0";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>
                <!--People Sections-->
                    <div id="people-block">
					<div class="fb-like like-facebook-home" data-href="<?php echo $url; ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
						<div class="row-fluid">
                            <div class="span12 people-right-block">
                                <div class="row-fluid">
                                    <div class="span12 detail-content">
                                        <p>
											<?php 
                                        		if (is_array($content) && count($content)) 
                                                	echo  !empty($content['Content']) ? $content['Content'] :  ' '; 
                                        	?>
                                        </p>
										<div class="pull-left share-box"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
