<?php $controller = ltrim(preg_replace("/([A-Z])/", " $1", 'Quận/Huyện'), ' ');?>

<div class="subject-title">
	<?php echo $this->text($controller) ?>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php //$this->renderTh('District Id'); ?>
                    <?php $this->renderTh('Tên Quận/Huyện');?>
                    
                    <th style="vertical-align: middle;">Chọn Quận/Huyện</th>
                </tr>
            </thead>

            <tbody lastest-news-content>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('districts/_partial/ajax-show-districts.phtml', array('dataRow'=>$row, 'cdistricts' => $this->cdistricts) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php //echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php //echo $this->paginationControl($this->paginator, 'Sliding', 'tutors/_partial/show-tutors-pagination.phtml'); ?>
    </div>
</div>
<script>
$("input[type=checkbox][class=modal-checkbox]").each(function() {
	$(this).live('click', function() {
		var districts = ''; var districtIds = '';
		if($(this).is(':checked')){
			var data = $.trim($('#TeachableDistricts').attr('subs'));
    		if($.trim(data) != '') data += ',';
        	arr =  $.unique((data+$(this).attr('id')).split(','));
        	districtIds = arr.join(","); //get unique string back with
        	$('#TeachableDistricts').attr('subs', districtIds);
			
    		var data = $.trim($('#TeachableDistricts').val());
    		if($.trim(data) != '') data += ',';
        	arr =  $.unique((data+$(this).val()).split(','));
        	districts = arr.join(","); //get unique string back with
        	$('#TeachableDistricts').val(districts);        	
    	}else{
    		var data = $.trim($('#TeachableDistricts').val());
        	y =  data.split(',');
    		y.splice( $.inArray($(this).val(), y), 1 );
    		districts = y.join(","); //get unique string back with
    		$('#TeachableDistricts').val(districts);

    		var data1 = $.trim($('#TeachableDistricts').attr('subs'));
    		//var data = $.trim($('#ClassSubjects').val());
        	y =  data1.split(',');
        	if(y.length){
	    		y.splice( $.inArray($(this).attr('id'), y), 1 );
	    		districtIds = y.join(","); //get unique string back with
        	}
    		$('#TeachableDistricts').attr('subs', districtIds);
        }
	});        
});                    
</script>