<div class="row-fluid">
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<?php 
    $controller = ltrim(preg_replace("/([A-Z])/", " $1", 'Districts'), ' ');
?>

<div class="row-fluid show-grid">
    <div class="span12">
        <h2>
            <?php echo $this->text($controller) ?>
        </h2>
    </div>
</div>
<?php
$typeSearchs = array(
    'All' => 'All',
    'DistrictId'                   => $this->text('DistrictId', false),
    'DistrictName'                 => $this->text('DistrictName', false),
    //'IsDisabled'                   => $this->text('IsDisabled', false),
);
$buttons = array(
    "<a class='btn btn-small btn-primary'  
        href='{$this->url(array('action' => 'add-'. $this->controller))}'>
        <i class='icon-plus'></i>
        Add {$this->text('Districts')}
    </a>"
);
echo $this->searchBar($typeSearchs, null, $buttons);

?>


<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php $this->renderTh('District Id'); ?>
                    <?php $this->renderTh('District Name'); ?>
                    <?php $this->renderTh('Is Disabled'); ?>
                    
                    <th style="vertical-align: middle;">Actions</th>
                </tr>
            </thead>

            <tbody>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('districts/_partial/show-districts.phtml', array('dataRow'=>$row) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </div>
</div>
