<?php $configsModel = new Application_Model_Configs();
		$showTitle = $configsModel->getConfigValue('ShowNewsTitle');
		if(isset($this->news) && count($this->news)):
		$url = FRONTEND_DOMAIN_NAME.Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
?>					
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=642583262446502&version=v2.0";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>
					<!--People Sections-->
                    <div id="people-block">
                    <?php if(isset($showTitle) && $showTitle):?>	
                         <h3><?php echo (!empty($this->news['Title'])) ? $this->news['Title'] : ""; ?></h3>
					<?php endif;?>
					<div style="height:20px;" class="fb-like" data-href="<?php echo $url; ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
                        <div class="row-fluid">
                            <div class="span12 people-right-block">
                                <div class="row-fluid">
                                    <div class="span12 detail-content">
                                        <p>
                                        	<?php echo $this->news['Content'];?>
                                        </p>
										<div class="pull-left share-box"></div>
										<?php if(count($this->otherNews)):?>
											<div class="span12">
												<ul class="other-news lastest-block">
													<li>Tin khác</li>
													<?php foreach($this->otherNews as $lastestNews):?>
													<li>
														<a href="/news/detail/id/<?php echo $lastestNews->NewsId.(empty($this->cate)?'':'/cate/'.$this->cate); ?>">
														<div class="pull-left">
															<?php  if(isset($lastestNews->ImageUrl) &&  !empty($lastestNews->ImageUrl) && file_exists(IMAGE_UPLOAD_PATH.$lastestNews->ImageUrl)):?>
															<img class="desc-news" src="<?php echo IMAGE_UPLOAD_URI.$lastestNews->ImageUrl?>" alt="<?php echo $lastestNews->ImageUrl?>"/>
															<img class="small-news" src="<?php echo IMAGE_UPLOAD_URI.$lastestNews->ImageUrl?>" alt="<?php echo $lastestNews->ImageUrl?>"/>
															<?php else:?>
															<img class="desc-news" src="/images/footer/logo_footer.png"/>
															<img class="small-news" src="/images/footer/logo_footer.png"/>
															<?php endif; ?>
															<span><?php echo $lastestNews->Title?></span>
															<?php $date = new Zend_Date($lastestNews->CreatedDate, DATE_FORMAT_DATABASE);?>
															<div class="lastest-date news-date"><?php echo $date->toString(DATE_FORMAT_ZEND);?></div>
														</div>
														</a>
													</li>
													<?php endforeach;?>
												 </ul>
											</div>
											<div class="clear-both"></div>                
										<?php endif;?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
<?php endif;?>                    