	<!--People Sections-->
          <div id="people-block">
               <div class="row-fluid">
                <!--Lastest News Sections-->
                <div class="span12 only-popular load-more-news1">
                    <div class="row-fluid">
                        <!-- <h3 class="bottom-news">Latest News</h3> -->
                        		<?php echo $this->renderBlock('lastest-news', $this)?>
                        <div id="lastest-news-content"></div>
                    </div>
                </div>
            </div>
        </div>