<?php if(count($this->paginator)):       
//convert object array to string for subject 
       function array2string($haystack, $needle){
       	$str="";
       	foreach($haystack as $k=>$i){
       		if(is_array($i)){ 
       			if(in_array($i['SubjectId'], $needle))
       				$str.= ','.$i['SubjectName'];
       				$str.=array2string($i, $needle);
       		}
       	}
       	return $str;
       }
?>
      <div class="row-fluid lastest-news-content">
			    <div class="row-fluid lastest-block">
			        <div class="featurette">			        
			               <?php $c = 0; foreach ($this->paginator as $key => $class):?>
						    <?php if (is_numeric($key)) : ?>
						            <div class="span4 pull-left classes <?php if($key % 3 ==0 ) echo 'third-class'?>">
							            <fieldset class="well the-fieldset">
							            	<legend>Mã số lớp học: <?php echo $class->ClassId?></legend>
								            <div class="lastest-date1 desc-news"><span>Lớp học: </span>
								            		<?php echo $class->ClassGrade ?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Môn học: </span>
								            		<?php 
								            			echo ltrim(array2string($this->subjects->toArray(), explode(',', $class->ClassSubjects)), ',');
								            		?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Số buổi: </span>
								            		<?php echo $class->ClassDaysOfWeek?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Thời gian: </span>
								            		<?php echo $class->ClassTime?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Yêu cầu: </span>
								            		<?php echo $class->ClassRequire?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Số ứng viên hiện tại: </span>
								            		<?php echo count(explode(',', $class->ClassTutors));?>
								            </div>
								            <div class="lastest-date1 desc-news"><span>Lương: </span>
								            		<?php echo $class->ClassCost?>
								            </div>
								            <div class="lastest-date1 desc-news class-address"><span>Địa chỉ: </span>
								            		<?php echo $class->ClassAddress?>
								            </div>
								            <div class="btn-apply">
								            	<a href="/classes/apply/id/<?php echo $class->ClassId; ?>">
								            		<button class="btn btn-primary">Ứng tuyển</button>
								            	</a>
								            </div>
								        </fieldset>			            
						            </div>
						    <?php endif; ?>
						<?php $c++;endforeach;?>			
			      	</div>      	
			      </div>
			<?php if(count($this->paginator) > 1):?>
			<div class="row-fluid">
			    <?php echo $this->paginationControl($this->paginator,'Sliding','/classes/block/list-classes-pagination.phtml'); ?>
			</div>
			<?php endif;?>
			
			<?php if($this->paginator->getCurrentItemCount() == CLASSES_ITEMS):?>
			<div class="loadmorenews"><div class="read-more-news">Xem thêm</div></div>
			<?php endif;?>
      </div>
<?php endif;?>                        