<?php $allParams = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    $cpage = (isset($allParams['page']) && $allParams['page'])? '/cate/'.$allParams['page']: '1';
?>
<?php if ($this->pageCount): ?>
<div class="pagination pagination-centered paginationControl bottom-news" total-page="<?php echo $this->pageCount;?>" current-page="1" 
page="<?php echo $cpage?>">
<ul>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li><a href="#lastest-news-content" onclick="scrollToView();loadPage('<?php echo '/tutors/ajax-get-tutors/page/'.$this->previous; ?>','<?php echo $this->previous;?>')">
    «
  </a> </li>
<?php else: ?>
  <li><span>«</span></li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href='#lastest-news-content' onclick="scrollToView();loadPage('<?php echo '/tutors/ajax-get-tutors/page/'.$page; ?>','<?php echo $page;?>')">
        <?php echo $page; ?>
    </a></li>
  <?php else: ?>
    <li><span class="active"><?php echo $page; ?></span></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li><a href="#lastest-news-content" onclick="scrollToView();loadPage('<?php echo '/tutors/ajax-get-tutors/page/'.$this->next; ?>','<?php echo $this->next;?>')">
    »
  </a></li>
<?php else: ?>
  <li><span>»</span></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>