<script type="text/javascript">
    var activeMenu = 'news';
</script>



<?php $staffsModel = new Application_Model_Staffs(); ?>

<div class="content about-main-content">
    <div class="container" style="position: relative;">

        <h1>Cat name: <?php echo $this->catName; ?></h1>
        <?php
                    foreach ($this->posts_array as $post){

            ?>
            <p><h1><a href="/news/detail/id/<?php echo $post->ID; ?>" class="button"><?php echo $post->post_title; ?></a></h1></p>
            <p><strong>Summary:</strong> <?php echo $post->post_excerpt; ?></p>
            <p><strong>Date Publish:</strong> <?php echo $post->post_date; ?> </p>

<?php $staff = $staffsModel->find($post->post_author)->current(); ?>

            <p><strong>Author: <?php echo $staff->FirstName; ?> <?php echo $staff->LastName; ?></strong> </p>
            <p><img src="<?php echo $staff->Avatar; ?>" /></p>
            <hr>
            <?php }?>
    </div>
</div>