<script type="text/javascript">
    var activeMenu = 'news';
</script>

    <!-- start block catelogy -->
    <?php echo $this->renderBlock("category-news", $this);?>
    <!-- end block catelogy -->

<div id="content-page" class="content">
<div class="container" style="position: relative;">
    <div class="row-fluid">
    <!-- start content news -->
    <div class="span9 content-news">
         <div class="span12">
               <a href="#"><img src="http://cdn.theglobalmail.org/cache/6e/e5/6ee59a78931941af9249464f32ce9c34.jpg" width="100%"></a>
         </div>

         <div class="span12 content-news-title">The Hobbit Holes That Saved New Zealand</div>

         <div class="span12">Jan 14, 2013</div>

        <div class="span12">content
        </div>

    </div>
    <!-- end content news -->

    <div id="right-content-news" class="span3">
    <!-- start block content author -->
    <?php echo $this->renderBlock("author", $this);?>
    <!-- end block content author -->

         <div class="span12 content-news-right">
               <a href="#"><img src="/images/social media.png" width="100%"></a>
         </div>

    <!-- start block news popular -->
    <?php echo $this->renderBlock("news-popular", $this);?>
    <!-- end block news popular -->
    </div>


</div>
</div>