<?php if(!empty($this->categories)):?>
<!-- start news categories block -->
<?php echo $this->renderBlock("category-news", $this);?>
<!-- end news categories block -->

<!-- start small news categories block -->
<?php echo $this->renderBlock("small-category-news", $this);?>
<!-- end small news categories block -->
<?php
    endif;
    if(!empty($this->allNewsData)):
        $newsData['TopFeatureNews'] = $this->allNewsData['TopFeatureNews'];
        $newsData['LastestNews']    = $this->allNewsData['LastestNews'];
        $newsData['PopularNews']    = $this->allNewsData['PopularNews'];
?>
<div class="content about-main-content">
    <div class="container" style="position: relative;">
        <div id="people-block" class="landing-page">
        <div class="round-border">
        <?php if(isset($newsData['TopFeatureNews'][0]['title']) && isset($newsData['TopFeatureNews'][0]['desc'])):?>
           <div class="row-fluid only-popular">
                <!--top feature image-->
                <div class="span8">
                    <div class="row-fluid"><a href="/news/detail/id/<?php echo $newsData['TopFeatureNews'][0]['id'].(empty($this->cate)?'':'/cate/'.$this->cate); ?>">
                        <div class="row-fluid large-image">
                            <?php if(isset($newsData['TopFeatureNews'][0]['image'])):?>
                                <img src="<?php echo $newsData['TopFeatureNews'][0]['image']['large']?>" alt="<?php echo $newsData['TopFeatureNews'][0]['title']?>"/>
                            <?php else:?>
                                <img src="http://placehold.it/770x385"/>
                            <?php endif;?>
                        </div></a>
                    </div>
                </div>
                <!--top feature content-->
                <div class="span4 feature-content">
                    <div class="row-fluid"><a href="/news/detail/id/<?php echo $newsData['TopFeatureNews'][0]['id'].(empty($this->cate)?'':'/cate/'.$this->cate); ?>">
                        <h3 class="news-desc">
                            <?php if(isset($newsData['TopFeatureNews'][0]['title'])):?>
                                <?php echo $newsData['TopFeatureNews'][0]['title']?>
                            <?php endif;?>
                        </h3>
                        <h4 class="news-desc">
                            <?php if(isset($newsData['TopFeatureNews'][0]['title'])):?>
                                <?php echo $newsData['TopFeatureNews'][0]['title']?>
                            <?php endif;?>
                        </h3></a>
                        <ul>
                            <?php if(isset($newsData['TopFeatureNews'][0]['desc'])):?>
                            <li class="desc-news"><?php echo $newsData['TopFeatureNews'][0]['desc']?></li>
                            <?php else:?>
                            <li class="desc-news">We are business solutions specialists, assisting our clients to connect people to their projects...and their projects to their technology.</li>
                            <li class="desc-news">4impact has fast become recognised as one of Australia's most trusted and respected services companies, assisting clients in Brisbane, Sydney, Melbourne and Canberra.</li>
                            <?php endif;?>
                            <li class="desc-news"></li>
                            <?php if(isset($newsData['TopFeatureNews'][0]['date'])):?>
                            <li class="news-date"><?php echo $newsData['TopFeatureNews'][0]['date']?></li>
                            <?php else:?>
                            <li>Feb 2, 2013</li>
                            <?php endif;?>
                            <?php if(isset($newsData['TopFeatureNews'][0]['author'])):?>
                            <li class="desc-news"><?php echo $newsData['TopFeatureNews'][0]['author']?></li>
                            <?php else:?>
                            <li class="desc-news">I am Zorro</li>
                            <?php endif;?>
                        </ul>
                    </div>
                </div>
            </div>
            <?php unset($newsData['TopFeatureNews'][0]);endif;?>
<?php /////////////////////////////////////////////////////////////////////////////////////////////?>
            <?php $topNews = count($newsData['TopFeatureNews']);
                if($topNews > 1):
            ?>
            <div class="vertical-seperator desc-news">&nbsp;</div>
            <div class="row-fluid only-popular">
                <?php $topNews = count($newsData['TopFeatureNews']);
                if($topNews == 2) $span = '6'; else $span = '4';
                foreach ($newsData['TopFeatureNews'] as $topNewsData):
                ?>
                <!--middle feature news-->
                <div class="row-fluid span<?php echo $span?> medium-image">
                    <div class="small-vertical-seperator">&nbsp;</div>
                    <div class="row-fluid">
                        <ul>
                            <a href="/news/detail/id/<?php echo $topNewsData['id'].(empty($this->cate)?'':'/cate/'.$this->cate); ?>">
                            <?php if(isset($topNewsData['image'])):?>
                            <li class="desc-news"><img src="<?php echo $topNewsData['image']['thumbnail']?>" alt="<?php echo $topNewsData['title']?>"/></li>
                            <li class="small-news"><img src="<?php echo $topNewsData['image']['large']?>" alt="<?php echo $topNewsData['title']?>"/></li>
                            <?php else:?>
                            <li><img src="http://placehold.it/380x190"/></li>
                            <?php endif;?>
                            <?php if(isset($topNewsData['title'])):?>
                            <li class="title-news"><h5 class="featurette-heading"><?php echo $topNewsData['title']?></h5></li>
                            <?php else:?>
                            <li>Heading 3</li>
                            <?php endif;?></a>
                            <?php if(isset($topNewsData['desc'])):?>
                            <li class="desc-news"><?php echo $topNewsData['desc']?></li>
                            <?php else:?>
                            <li class="desc-news">We are business solutions specialists, assisting our clients to connect people to their projects...and their projects to their technology.</li>
                            <?php endif;?>
                            <?php if(isset($topNewsData['date'])):?>
                            <li class="news-date"><?php echo $topNewsData['date']?></li>
                            <?php else:?>
                            <li>Feb 2, 2013</li>
                            <?php endif;?>
                        </ul>
                    </div>
                </div>
                <?php endforeach;?>
            </div>
            <?php endif;?>
            </div>
<?php /////////////////////////////////////////////////////////////////////////////////////////////?>
<!--            <div class="vertical-seperator desc-news">&nbsp;</div>-->
            <div class="row-fluid">
                <!--Lastest News Sections-->
                <div class="span8 only-popular load-more-news">
                    <div class="row-fluid">
                        <h3 class="bottom-news">Latest News</h3>
                        <?php if(count($newsData['LastestNews'])):?>
                        <div class="row-fluid lastest-news-content">
                            <?php echo $this->renderBlock('lastest-news', $this)?>
                        </div>
                        <div id="lastest-news-content"></div>
                        <?php endif;?>
                    </div>
                </div>

                <!--Popular News Sections-->
                <div class="span4 row-fluid popular-wrapper">
                    <?php echo $this->renderBlock('popular-news', $this)?>
                </div>
            </div>
        </div>
    </div>
</div>
<!--
<div id="scroll-to-top" style="display: none;">
    <a href="#people-block"><img src="/images/icon_top.png"/></a>
</div> -->
<div style="clear:both"></div>
<?php endif;?>
<!--[if IE 8]>
    <style type="text/css">
    .round-border {margin-top: 10px}
    .load-more-news {margin-bottom:-50px !important;}
    .content {padding-top: 10px !important;}
    </style>
<![endif]-->
<script type="text/javascript">
    var activeMenu = 'news';
    var activeSubMenu = "<?php echo (empty($this->cate)?'all':'cate-'.$this->cate)?>";
</script>