<div class="content-top">
	    <div class="container">
	        <div class="row-fluid">
	        	<?php //if(count($this->LeftContentTop)):?>
	        	<div id="content-top-left" class="span2 content-top-left"> 
	        			<div class="content-top-left-title">
	        					<img src="/images/icons/16x16/graduation-hat.png" />
	        					PHỤ HUYNH 
	        			</div>
	        			<ul class="content-top-menu">
	        				<?php foreach ($this->LeftContentTop as $item):?>
	        				<li>
	        					<img src="/images/icons/8x8/graduation-hat.png" />
	        					 <a href="<?php echo $item['MenuUrl']; ?>">
	        					 	<?php echo $item['MenuName']; ?>
	        					 </a>
	        				</li>
	        				<?php endforeach; ?>
	        			</ul>
	        	</div>
	        	<?php //endif; ?>
	        	<div id="content-top-center" class="span8 content-top-center">
	        		<div id="myCarousel" class="carousel slide">
						  <ol class="carousel-indicators">
						    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
						    <li data-target="#myCarousel" data-slide-to="1"></li>
						    <li data-target="#myCarousel" data-slide-to="2"></li>
						  </ol>
						  <!-- Carousel items -->
						  <div class="carousel-inner">
						    <div class="active item">
						    	<img src="/images/carousel/bootstrap-mdo-sfmoma-01.jpg" alt="">
						    	<div class="carousel-caption">
			                      <h4>Kính gởi Quý Phụ Huynh …</h4>
			                      <p>Đầu tiên, TTGS chúng tôi gởi lời chúc sức khỏe, hạnh phúc đến gia đình
Quý Phụ Huynh!
			                      </p>
			                    </div>
						    </div>	
						    <div class="item">
						    	<img src="/images/carousel/bang_gia.jpg" alt="">
				                    <div class="carousel-caption">
				                      <h4>Đội ngũ </h4>
				                      <p>+ Giáo viên Kinh nghiệm
   	         		      + Sinh viên ĐHSP&các trường đại học uy tín
				                      </p>
				                    </div>
						    </div>
						    <div class="item">
						    	<img src="/images/carousel/bootstrap-mdo-sfmoma-03.jpg" alt="">
				                    <div class="carousel-caption">
				                      <h4>Vì sự thành đạt ngày mai</h4>
				                      <p>Quý Phụ huynh hãy đầu tư cho con em mình từ hôm nay!</p>
				                    </div>
						     </div>
						  </div>
						  <!-- Carousel nav -->
						  <!-- <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
						  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a> -->
						</div>
	        	</div>
	        	<script>$('.carousel').carousel();</script>
	        	<?php //if(count($this->RightContentTop)):?>
	        	<div id="content-top-right" class="span2 content-top-right">
	        		  <div class="content-top-right-title">
	        					<img src="/images/icons/16x16/leather-bag.png" style="vertical-align: top;"/>
	        					GIA SƯ
	        			</div>
	        			<ul class="content-top-menu">
	        				<?php foreach ($this->RightContentTop as $item):?>
		        				<li>
		        					<img src="/images/icons/8x8/leather-bag.png" />
		        					 <a href="<?php echo $item['MenuUrl']; ?>">
		        					 	<?php echo $item['MenuName']; ?>
		        					 </a>
		        				</li>
		        				<?php endforeach; ?>
		        			</ul>
		        	</div>
	        	<?php //endif; ?>
	        </div>
	    </div>
	</div>