<div class="span">
    <div class="container">
        <div class="row-fluid">
        	<div id="content-top-left" class="span2">
        			<ul class="content-top-menu">
        				<li>ĐĂNG KÍ TÌM GS</li>
        				<li>BẢNG HỌC PHÍ THAM KHẢO</li>
        				<li>PHỤ HUYNH CẦN BIẾT</li>
        			</ul>
        	</div>
        	
        	<div id="content-top-center" class="span8">
        	
        	</div>
        	
        	<div id="content-top-right" class="span2">
        		<ul class="content-top-menu">
        				<li>ĐĂNG KÍ LÀM GIA SƯ</li>
        				<li>LỚP HIỆN CÓ</li>
        				<li>NỘI QUY NHẬN LỚP</li>
        			</ul>
        	</div>
        </div>
    </div>
</div>