<!--News Sections-->
	                <div class="span2 news-block">
	<!--                    <h3>News</h3>-->
	<!--                     <div class="content-top">	 -->
<!-- 						    <div class="container"> -->
	<!-- 					        <div class="row-fluid"> -->
						        	<div id="content-middle-left" class="span2">
						        			<div class="content-top-left-title">
						        					<img src="/images/icons/16x16/abc.png" />
						        					TIN TỨC
						        			</div>
						        			<ul class="content-top-menu">
						        				<li>
						        					<img src="/images/icons/8x8/abc.png" />
						        					 <a href="/">
						        					 	Giáo dục
						        					 </a>
						        				</li>
						        				<li>
						        					<img src="/images/icons/8x8/abc.png" />
						        					 <a href="/">
						        					 	Gia sư Tâm
						        					 </a>
						        				</li>
						        				<li>
						        					<img src="/images/icons/8x8/abc.png" />
						        					 <a href="/">
						        					 	Gia sư dạy kèm
						        					 </a>
						        				</li>
						        			</ul>
						        	</div>
						        	
						        	<div id="content-middle-left" class="span2">
						        			<div class="content-top-left-title">
						        					<img src="/images/icons/16x16/laptop.png" />
						        					HỖ TRỢ
						        			</div>
						        			<div class="content-left">
								             	<!-- <form> -->
												    <fieldset class="well the-fieldset">
												        <legend class="the-legend">Tư Vấn</legend>
												        <a>
												        	<img style="border:0" align="middle" src="http://opi.yahoo.com/online?u=giasu42a&amp;m=g&amp;t=1" title="Tư Vấn">
												        </a><br>Tel: 0919176446
												    </fieldset>
												<!-- </form> -->
												<form>
												    <fieldset class="well the-fieldset">
												        <legend class="the-legend">Tư Vấn</legend>
												        <a>
												        	<img style="border:0" align="middle" src="http://opi.yahoo.com/online?u=giasu42a&amp;m=g&amp;t=1" title="Tư Vấn">
												        </a><br>Tel: 0909361963
												    </fieldset>
												</form>	                   
								             </div>
								             
								             
						        	</div>
	<!-- 					        </div> -->
	<!-- 					    </div> -->
<!-- 						</div> -->
	                </div>