<?php $info = ''; require_once APPLICATION_PATH . '/../library/Function/counter.php';?>
<!--News Sections-->
	                <div class="span2 news-block <?php echo (isset($this->violetBg) && $this->violetBg)?$this->violetBg:'';?>">
	                		<?php if(count($this->LeftContentMiddle)):?>
						        	<div id="content-middle-left" class="span2">
						        			<div class="content-top-left-title">
						        					<img src="/images/icons/16x16/abc.png" />
						        					TIN TỨC
						        			</div>
						        			<ul class="content-top-menu">
						        				<?php foreach ($this->LeftContentMiddle as $item):?>
						        				<li>
						        					<img src="/images/icons/8x8/abc.png" />
						        					 <a href="<?php echo $item['MenuUrl']; ?>">
						        					 	<?php echo $item['MenuName']; ?>
						        					 </a>
						        				</li>
						        				<?php endforeach; ?>
						        			</ul>
						        	</div>
						     <?php endif; ?>
						        	<div id="content-middle-left" class="span2">
						        			<div class="content-top-left-title">
						        					<img src="/images/icons/16x16/laptop.png" />
						        					HỖ TRỢ
						        			</div>
						        			<div class="content-left">
								             	<form>
												    <fieldset class="well the-fieldset">
												        <legend class="the-legend">Tư Vấn</legend>
												        <a href="ymsgr:sendim?giasutam">
												        	<img style="border:0" align="middle" src="http://opi.yahoo.com/online?u=giasutam&amp;m=g&amp;t=1" title="Tư Vấn">
												        </a><br><strong>Tel: 0919176446</strong>
												    </fieldset>
												</form>
												<form>
												    <fieldset class="well the-fieldset">
												        <legend class="the-legend">Tư Vấn</legend>
												        <a href="ymsgr:sendim?tamlehung1983">
												        	<img style="border:0" align="middle" src="http://opi.yahoo.com/online?u=tamlehung1983&amp;m=g&amp;t=1" title="Tư Vấn">
												        </a><br><strong>Tel: 0909361963</strong>
												    </fieldset>
												</form>	                   
								             </div>
						        	</div>
						        	
						        	<div id="content-middle-left" class="span2">
						        			<div class="content-top-left-title">
						        					<img src="/images/icons/16x16/globe.png" />
						        					THỐNG KÊ
						        			</div>
						        			<ul class="content-top-menu">
						        				<?php if(!empty($info)): $info = explode(':', $info);?>
						        				<li>
						        					<img src="/images/icons/8x8/globe.png" />
						        					 <strong>Tổng truy cập: <?php echo $info[0];?></strong>
						        				</li>
						        				<li>
						        					<img src="/images/icons/8x8/globe.png" />
						        					 <strong>Đang truy cập:  <?php echo $info[1];?></strong>
						        				</li>
						        				<?php endif; ?>
						        			</ul>
						        	</div>
									
									<div id="content-middle-left" class="span2 lg-share-box">
						        			<div class="content-top-left-title">
						        					<img src="/images/icons/16x16/share.png" />
						        					CHIA SẺ
						        			</div>
						        			<div id="social" class="social"></div>
						        	</div>
									<script>						        	
								        	$(function() {	
								        	    $("#social").socialButtonsShare({
								        	      socialNetworks: ["facebook", "twitter", "googleplus"],
								        	      url: $('.URL').attr('href'),
								        	      text: "Gia sư Tâm",
								        	      sharelabel: false,
												  counter: true,
								        	      verticalAlign: false
								        	    }, {
								        	      facebook: {
								        	        title: ""
								        	      },
								        	      twitter: {
								        	        title: ""
								        	      },
								        	      googleplus: {
								        	        title: ""
								        	      }
								        	    });
								        	 });
									</script>
	                </div>