<?php
echo $this->doctype();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> 
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=1">
        <!-- The fav icon -->
        <link href="/images/favicon.ico" rel="SHORTCUT ICON">
        <?php
        getStyleContents($this, $controller, $action);
        getScriptContents($this, $controller, $action);
        ?>
        <style>
            body{
                background: none;
            }             
        </style>
        <script src="/scripts/scroll-iframe.js" type="text/javascript"></script>
    </head>    
    <body data-spy="scroll">
        <div id="contentall">
            <center>
                <?php //echo $this->render('header.phtml'); ?>
                <?php echo $this->layout()->content; ?>
                <?php //echo $this->render('footer.phtml');  ?>
            </center>
        </div>
    </body>
</html>
