    <div class="footer">
        <div class="container padding-top-footer">
            <div class="row-fluid" style="position: relative;">
                <div id="social-link-footer" class="span4" style="">
                    <?php echo $this->render('/block/social-links.phtml'); ?>
                </div>
                <div id="let-talk-footer" class="span6">
                    <?php echo $this->render('/block/lets-talk.phtml'); ?>
                </div>
                <div id="logo-footer" class="span2">
                    <?php echo $this->render('/block/part-of-the-4impact-group.phtml'); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="URL" value="<?php  echo "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']; ?>"></div>


<script type="text/javascript">

function showFooterInSmallViewPort(){

    var bodyWidth = $(window).width();
    if(bodyWidth > 767){
        /* $(".social-links-linkedIn").tooltip();
        $(".social-links-twitter").tooltip();
        $(".social-links-facebook").tooltip();
        $(".social-links-google-plus").tooltip(); */
        $(".social-links-linkedIn").hover(function(){
            $(".tooltip").show();
        });
        $(".social-links-twitter").hover(function(){
          $(".tooltip").show();
        });
        $(".social-links-facebook").hover(function(){
          $(".tooltip").show();
        });
        $(".social-links-google-plus").hover(function(){
          $(".tooltip").show();
        });
    }
    else{
        $(".social-links-linkedIn").hover(function(){
              $(".tooltip").hide();
        });
        $(".social-links-twitter").hover(function(){
            $(".tooltip").hide();
        });
        $(".social-links-facebook").hover(function(){
            $(".tooltip").hide();
        });
        $(".social-links-google-plus").hover(function(){
            $(".tooltip").hide();
        });
    }
}

function showGroupSocialLinkInSmall(){
    var bodyWidth = $(window).width();
    if(bodyWidth < 767){
        var countSocialLink = eval($(".social-links").attr("count"));
        var widthOneSocialLink = "width: "+100/countSocialLink + "% !important";
        $(".one-link-footer").attr("style",widthOneSocialLink);
    }else{
        $(".one-link-footer").attr("style", "width: auto");
    }
}

function editCssForIe8(){
    if($.browser.msie  && parseInt($.browser.version, 10) === 8){
        var bodyWidth = $(window).width();
        if(bodyWidth < 767){
            $(".content-right").attr("style","text-align: left;margin: 0px !important;padding-left: 5px;padding-right: 5px;");
            $(".image-left").attr("style","margin: 0px !important;padding: 0px !important;");
        }
        else{
            $(".content-right").attr("style","");
            $(".image-left").attr("style","");
        }
    }
}

showGroupSocialLinkInSmall();
showFooterInSmallViewPort();


$(window).resize(function () {
    showGroupSocialLinkInSmall();
    showFooterInSmallViewPort();
    editCssForIe8();
});


$(document).ready(function() {
    editCssForIe8();
});
</script>