<div class="top-banner header1 logo1">
    <div class="container">
        <div class="row-fluid">
            <div class="span12">         
                      <img src="/images/top_banner.jpg" />
            </div>
             <div class="span12 menu-small-viewport"> 
                      <span class="left-nav-triangle collapsed" style="float: left">&nbsp;</span>
                      <span>Chuyển trang</span>
                      <span class="right-nav-triangle collapsed" style="float:right">&nbsp;</span> 
             </div> 
         </div>
     </div>  
</div>  