<div class="top-banner">
    <div class="container">
        <div class="row-fluid">
            <div class="span12 top-logo"></div>
             <div id="menu-small-viewport" class="span12 menu-small-viewport"> 
                      <span class="left-nav-triangle" style="float: left"><i class="icon-chevron-down icon-white"></i></span>
                      <span>Chuyển trang</span>
                      <span class="right-nav-triangle" style="float:right"><i class="icon-chevron-down icon-white"></i></span> 
             </div> 
         </div>
     </div>  
</div>  