<?php
echo $this->doctype();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
getHeaders($this, $controller, $action);

$menusModel = new Application_Model_Menus();
$menus = $menusModel->groupMenuByParent($menusModel->fetchAll($menusModel->getAllAvaiabled()));
$configsModel = new Application_Model_Configs();
$menuTop = $menusModel->getMenu($menus, $configsModel->getConfigValue('TopMenu')); 
$leftContentTop = $menusModel->getMenu($menus, $configsModel->getConfigValue('LeftContentTopParent'), true);
$rightContentTop = $menusModel->getMenu($menus, $configsModel->getConfigValue('RightContentTopParent'), true);
$leftContentMiddle = $menusModel->getMenu($menus, $configsModel->getConfigValue('LeftContentMiddleParent'), true);
$contentTop = array('LeftContentTop' => $leftContentTop, 'RightContentTop' => $rightContentTop);
?>
<html>
    <head>
        <?php 
	        getStyleContents($this, $controller, $action);
	        getScriptContents($this, $controller, $action); 
        ?>
        <!--[if IE 8]>
        <link rel="stylesheet" type="text/css" href="/styles/ie8.css" />
        <script src="/scripts/ie8.js" type="text/javascript"></script>
        <![endif]-->

        <!--[if gt IE 8]><link rel="stylesheet" type="text/css" href="/styles/gtei8.css" /><![endif]-->

        <!-- The fav icon -->
        <link href="/images/logo_256px.ico" rel="SHORTCUT ICON">
    </head>

    <body data-spy="scroll">
        <div id="contentall">
            <?php echo $this->render('header.phtml'); ?>
            <?php echo $this->renderLayoutBlock('menu-top.phtml', $this, array('TopMenu' => $menuTop)); ?>            
            <div class="content">
				<?php echo $this->renderLayoutBlock('content-top.phtml', $this, $contentTop); ?>
				<div class="content-main">
					<div id="home-page">
						<div class="container">
				            <div class="row-fluid">
									<!--News Sections-->
				                	<?php echo $this->renderLayoutBlock('content-left.phtml', $this, array('LeftContentMiddle' => $leftContentMiddle)); ?>
				             		<!--Main Sections-->
					                <div class="span10 content-block">            
	            						<?php echo $this->layout()->content; ?>            
	            	                </div>
				               </div> 	
				            </div>
				        </div>
					</div>
				</div>
        	<?php echo $this->render('footer.phtml'); ?>
       	 </div>
    </body>
</html>
