<?php
echo $this->doctype();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
getHeaders($this, $controller, $action);

$menusModel = new Application_Model_Menus();
$menus = $menusModel->groupMenuByParent($menusModel->fetchAll($menusModel->getAllAvaiabled()));

$configsModel = new Application_Model_Configs();
$violetBg = $configsModel->getConfigValue('VioletBackgroundColor');
$menuTop = $menusModel->getMenu($menus, $configsModel->getConfigValue('TopMenu')); 
$leftContentTop = $menusModel->getMenu($menus, $configsModel->getConfigValue('LeftContentTopParent'), true);
$rightContentTop = $menusModel->getMenu($menus, $configsModel->getConfigValue('RightContentTopParent'), true);
$leftContentMiddle = $menusModel->getMenu($menus, $configsModel->getConfigValue('LeftContentMiddleParent'), true);

$imagesModel = new Application_Model_Images();
$middleContentTop = $imagesModel->fetchAll($imagesModel->getAllAvaiabled($configsModel->getConfigValue('TopContentMiddle')));
$contentTop = array('LeftContentTop' => $leftContentTop, 'MiddleContentTop' => $middleContentTop, 'RightContentTop' => $rightContentTop, 'violetBg' => $violetBg);
$leftContent = array('LeftContentMiddle' => $leftContentMiddle, 'violetBg' => $violetBg);
?>
<html>
    <head>
        <?php if (($controller == 'user' && $action == 'contact') || ($controller == 'tutors' && $action == 'register')):?>
        <script type="text/javascript" src="/scripts/tinymce/js/tinymce/tinymce.min.js"></script>
         <?php endif;
	        getStyleContents($this, $controller, $action);
	        getScriptContents($this, $controller, $action); 
        ?>
        <!--[if IE 8]>
        <link rel="stylesheet" type="text/css" href="/styles/ie8.css" />
        <script src="/scripts/ie8.js" type="text/javascript"></script>
        <![endif]-->

        <!--[if gt IE 8]><link rel="stylesheet" type="text/css" href="/styles/gtei8.css" /><![endif]-->

        <!-- The fav icon -->
        <link href="/images/logo_256px.ico" rel="SHORTCUT ICON">
    </head>

    <body data-spy="scroll1">
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-55647043-1', 'auto');
		  ga('send', 'pageview');

		</script>
        <div id="contentall">
            <?php echo $this->render('header.phtml'); ?>
            <?php echo $this->renderLayoutBlock('menu-top.phtml', $this, array('TopMenu' => $menuTop)); ?>            
            <div class="content">
				<?php echo $this->renderLayoutBlock('content-top.phtml', $this, $contentTop); ?>
				<div class="content-main">
					<div id="home-page">
						<div class="container">
				            <div class="row-fluid">
									<!--News Sections-->
				                	<?php echo $this->renderLayoutBlock('content-left.phtml', $this, $leftContent); ?>
				             		<!--Main Sections-->
					                <div class="span10 content-block">            
	            						<?php echo $this->layout()->content; ?>            
	            	                </div>
				               </div> 	
				            </div>
				        </div>
					</div>
				</div>
				<div class="scrollToTop" title="Đầu trang" style="bottom: 25px;"><i class="icon-chevron-up"></i></div>
        	<?php echo $this->render('footer.phtml'); ?>
       	 </div>
		<?php if ($controller != 'index'){?> <script>scrollToViewContent();</script><?php } ?>
    </body>
</html>
