<?php
echo $this->doctype();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
getHeaders($this, $controller, $action);
?>
<html>
    <head>
        <?php if ($controller == 'about' && $action == 'index')://import google map api ?>
            <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
            <?php
        endif;
        getStyleContents($this, $controller, $action);
        getScriptContents($this, $controller, $action);
        if ($controller == 'index' && $action == 'index'):
            $snapShots = $this->common()->getImageCrazyEgg();
            ?>
            <script type="text/javascript">
                var myImage1 = new Image();
                myImage1.src = '<?php echo $snapShots["screenshot_url"] ?>';
                var myImage2 = new Image();
                myImage2.src = '<?php echo $snapShots["heatmap_url"] ?>';
            </script>
        <?php endif; ?>
        <!--[if IE 8]>
        <link rel="stylesheet" type="text/css" href="/styles/ie8.css" />
        <script src="/scripts/ie8.js" type="text/javascript"></script>
        <![endif]-->

        <!--[if gt IE 8]><link rel="stylesheet" type="text/css" href="/styles/gtei8.css" /><![endif]-->

        <!-- The fav icon -->
        <link href="/images/favicon.ico" rel="SHORTCUT ICON">
    </head>

    <body data-spy="scroll">
        <div id="contentall">
            <?php echo $this->render('menu-top.phtml'); ?>
            <?php echo $this->layout()->content; ?>
            <?php echo $this->render('footer.phtml'); ?>
        </div>
        <!-- Phuc ga -->
        <!--<script src="/scripts/sroll-iframe.js" type="text/javascript"></script>-->
        <script>
            $('body').waitForImages(function() {
                $.getScript("/scripts/scroll-iframe.js");
            });
        </script>
    </body>
</html>