<?php
echo $this->doctype();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
getHeaders($this, $controller, $action);
?>
<html>
    <head>
        <?php if ($controller == 'about' && $action == 'index')://import google map api ?>
            <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
        <?php
        			endif;
	        getStyleContents($this, $controller, $action);
	        getScriptContents($this, $controller, $action);
        ?>
        <!--[if IE 8]>
        <link rel="stylesheet" type="text/css" href="/styles/ie8.css" />
        <script src="/scripts/ie8.js" type="text/javascript"></script>
        <![endif]-->

        <!--[if gt IE 8]><link rel="stylesheet" type="text/css" href="/styles/gtei8.css" /><![endif]-->

        <!-- The fav icon -->
        <link href="/images/logo_256px.ico" rel="SHORTCUT ICON">
    </head>

    <body data-spy="scroll">
        <div id="contentall">
            <?php echo $this->render('header.phtml'); ?>
            <?php echo $this->render('menu-top.phtml'); ?>            
            <div class="content">
				<?php echo $this->render('content-top.phtml'); ?>
				<div class="content-main">
					<div id="home-page">
						<div class="container">
				            <div class="row-fluid">
									<!--News Sections-->
				                	<?php echo $this->render('content-left.phtml'); ?>
				             		<!--Main Sections-->
					                <div class="span10 content-block">            
	            						<?php echo $this->layout()->content; ?>            
	            	                </div>
				               </div> 	
				            </div>
				        </div>
					</div>
				</div>
        	<?php echo $this->render('footer.phtml'); ?>
       	 </div>
        <!--<script src="/scripts/sroll-iframe.js" type="text/javascript"></script>-->
        <script>
            $('body').waitForImages(function() {
                $.getScript("/scripts/scroll-iframe.js");
            });
        </script>
    </body>
</html>
