<div class="menu">
    <div class="container">
        <div class="row-fluid">
            <div id="menus" class="span">
                <ul class="navigation sf-menu display-menu">
                    <?php foreach ($this->TopMenu as $menu) : ?>
                        <?php if (isset($menu['ClassName']) && $menu['ClassName'] != '') : ?>
                            <li class="<?php echo $menu['ClassName']; ?> <?php echo $menu['MenuCode']; ?>">
                                <a href="<?php echo $menu['MenuUrl']; ?>">
                                    <span><?php echo $menu['MenuName']; ?></span>
                                </a>

                                <?php if (isset($menu['childs']) && sizeof($menu['childs'])) : ?>
                                    <ul>
                                        <?php foreach ($menu['childs'] as $key => $child) : ?>
                                            <li class="<?php echo $child['ClassName']; ?> <?php echo $child['MenuCode']; ?>">
                                                <a href="<?php echo $child['MenuUrl']; ?>">
                                                    <span><?php echo $child['MenuName']; ?></span>
                                                </a>

                                                <?php if (sizeof($menu['childs']) > $key + 1) : ?>
                                                    <div></div>
                                                <?php endif; ?>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>