<?php $menusModel = new Application_Model_Menus(); ?>
<?php
$menus = $menusModel->groupMenuByParent($menusModel->fetchAll($menusModel->getAllAvaiabled()));
$url = base64_encode($this->common()->curPageURL());
?>

<div class="span">
    <div class="container">
        <div class="row-fluid">
<!--             <div class="span4"> -->
<!--                         <div class="menu-small-viewport"> -->
<!--                             <span>Menu</span> -->
<!--                         </div> -->
<!--             </div> -->
            <div id="menus" class="span12">
                <ul class="navigation sf-menu display-menu">
                    <?php foreach ($menus as $menu) : ?>
                        <?php if (isset($menu['ClassName']) && $menu['ClassName'] != '') : ?>
                            <li class="<?php echo $menu['ClassName']; ?> <?php echo $menu['MenuCode']; ?>">
                                <a href="<?php echo $menu['MenuUrl']; ?>">
                                    <span><?php echo $menu['MenuName']; ?></span>
                                </a>

                                <?php if (isset($menu['childs']) && sizeof($menu['childs'])) : ?>
                                    <ul>
                                        <?php foreach ($menu['childs'] as $key => $child) : ?>
                                            <li class="<?php echo $child['ClassName']; ?> <?php echo $child['MenuCode']; ?>">
                                                <a href="<?php echo $child['MenuUrl']; ?>">
                                                    <span><?php echo $child['MenuName']; ?></span>
                                                </a>

                                                <?php if (sizeof($menu['childs']) > $key + 1) : ?>
                                                    <div></div>
                                                <?php endif; ?>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>