<p>
Xin chào <?php echo $this->name; ?>,<br/><br/>
Cảm ơn bạn đã đăng ký làm gia sư với <a href="http://giasu-tam.com" target="_blank">Giasu-tam.com</a><br/><br/>
<b>Mã số của bạn: <?php echo $this->tutorId; ?></b><br/><br/>
<i>Mã số</i> được dùng khi bạn muốn ứng tuyển vào <a href="http://giasu-tam.com/classes/show-classes" target="_blank">Lớp dạy hiện có</a><br/><br/><br/>
Chúng tôi sẽ liên hệ ngay khi cập nhật được thông tin.
</p>