<?php $controller = ltrim(preg_replace("/([A-Z])/", " $1", 'Môn Học'), ' ');?>

<div class="subject-title">
	<?php echo $this->text($controller) ?>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php //$this->renderTh('Subject Id'); ?>
                    <?php $this->renderTh('Tên Môn Học'); ?>
                    
                    <th style="vertical-align: middle;">Chọn Môn Học</th>
                </tr>
            </thead>

            <tbody lastest-news-content>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('subjects/_partial/ajax-show-subjects.phtml', array('dataRow'=>$row, 'csubjects' => $this->csubjects) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php //echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php //echo $this->paginationControl($this->paginator, 'Sliding', 'tutors/_partial/show-tutors-pagination.phtml'); ?>
    </div>
</div>
<script>
$("input[type=checkbox][class=modal-checkbox]").each(function() {
	$(this).live('click', function() {
		var subjects = ''; var subjectIds = '';
		var url = '/subjects/ajax-convert-subjects';
    	if($(this).is(':checked')){
    		var data = $.trim($('#TeachableSubjects').attr('subs'));
    		if($.trim(data) != '') data += ',';
        	arr =  $.unique((data+$(this).attr('id')).split(','));
        	subjectIds = arr.join(","); //get unique string back with
        	$('#TeachableSubjects').attr('subs', subjectIds);

        	var data1 = $.trim($('#TeachableSubjects').val());
        	if($.trim(data) != '') data1 += ',';
        	arr =  $.unique((data1+$(this).val()).split(','));
        	subjects = arr.join(","); //get unique string back with
        	$('#TeachableSubjects').val(subjects);

    	}else{
    		//var data = $.trim($('#TeachableSubjects').attr('subs'));
    		var data = $.trim($('#TeachableSubjects').val());
        	y =  data.split(',');
        	if(y.length){
	    		y.splice( $.inArray($(this).val(), y), 1 );
	    		subjects = y.join(","); //get unique string back with
        	}
    		$('#TeachableSubjects').val(subjects);

    		var data1 = $.trim($('#TeachableSubjects').attr('subs'));
    		//var data = $.trim($('#TeachableSubjects').val());
        	y =  data1.split(',');
        	if(y.length){
	    		y.splice( $.inArray($(this).attr('id'), y), 1 );
	    		subjectIds = y.join(","); //get unique string back with
        	}
    		$('#TeachableSubjects').attr('subs', subjectIds);

        }
	});        
});                    
</script>