        <div class="container-fluid">
        <div class="row-fluid">

            <div class="row-fluid">
                <div class="span12 center login-header">
                    <h2>Welcome to 4impact mobile administration website</h2>
                </div><!--/span-->
            </div><!--/row-->

            <div class="row-fluid">
                <div class="well span5 center login-box">
                    <div class="alert  <?php if((isset($this->rs) && !$this->rs) || isset($this->rsEmpty)) echo 'alert-error';
                    else if(isset($this->rs) && $this->rs) echo 'alert-success';
                    else echo 'alert-info'?>">
                        <?php
                             if(!isset($this->rsSendMail)){
                                if(isset($this->rs) && $this->rs) echo "We've sent you an email with a new password.";
                                else if(isset($this->rs) && !$this->rs) echo 'Email is invalid or not exists.';
                                else echo "Please enter the email address you use to login to this website. We'll send a new password to this email address.";
                             }
                             else echo $this->rsSendMail[1];
                        ?>
                    </div>
                    <?php if(isset($this->rs) && $this->rs):?>
                    <form class="form-horizontal" action="/admin/users/login" method="get">
                    <button class="btn btn-medium btn-primary" href="/admin/users/login"><i class="icon-chevron-left icon-white"></i>Back to login</button>
                    </form>
                    <?php else:?>
                    <form class="form-horizontal" action="/admin/users/forgot-password" method="post">
                        <fieldset>
                            <div class="input-prepend" title="Username" data-rel="tooltip">
                                <span class="add-on"><i class="icon-user"></i></span><input autofocus class="input-large span10" name="username" id="username" type="text" value="" />
                            </div>
                            <div class="clearfix"></div>

                            <p class="center span5">
                            <button id="btnLogin" type="submit" class="btn btn-primary">Continue</button>
                            </p>

                            <div class="clearfix"></div>
                            <p class="center"><a href="/admin/users/login"><i class="icon-chevron-left"></i> Back to login</a></p>
                        </fieldset>
                    </form>
                    <?php endif;?>
                </div><!--/span-->
            </div><!--/row-->
                </div><!--/fluid-row-->

    </div><!--/.fluid-container-->

    <script type="text/javascript">
    $(".form-horizontal").submit(function(){
        $("#btnLogin").attr("disabled","disabled");
    });
    </script>