
            <div class="row-fluid">
                <?php if(!empty($this->message) && isset($this->message[0])):?>
                <?php $message = explode("/", $this->message[0]);?>
                <div class="span12">
                     <div class="alert alert-<?php echo $message[0];?>">
                        <button class="close" data-dismiss="alert" type="button">x</button>
                        <?php echo $message[1];?>
                        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
                    </div>
                </div>
                <?php endif;?>
            </div>

            <div class="row-fluid">
                <div class="span12">
                <p><a href="/admin" class="btn btn-medium btn-primary"><i class="icon-chevron-left icon-white"></i> Home</a>
                <a href="/admin/users/add" class="btn btn-medium btn-primary"><i class="icon-plus-sign icon-white"></i> Add</a></p>
                </div>
            </div>

            <div class="row-fluid sortable">
                <div class="box span12">
                    <div class="box-header well" data-original-title>
                        <h2><i class="icon-user"></i> Users</h2>
                    </div>
                    <div class="box-content">

                        <table class="table table-striped table-bordered bootstrap-datatable datatable">
                          <thead>
                              <tr>
                                  <th>Full Name</th>
                                  <th>Email</th>
                                  <th>Last Login</th>
                                  <th>Status</th>
                                  <th>Actions</th>
                              </tr>
                          </thead>
                          <tbody>
                          <?php
                          if(count($this->Users)):
                          foreach ($this->Users as $key=>$user):?>
                          <tr>
                                <td><?php echo $user->FirstName;?> <?php echo $user->LastName;?></td>
                                <td class="center"><?php echo $user->Email;?></td>
                                <td class="center"><?php
                                    if(!empty($user->LastLogin)){
                                        $lastLogin = new Zend_Date($user->LastLogin,DATE_FORMAT_DATABASE);echo $lastLogin->toString(DATE_FORMAT_FULL);
                                    }
                                    else echo 'N/A';
                                ?></td>
                                <td class="center">
                                    <?php if(!$user->IsDisabled):?><span class="label label-success">Active</span><?php endif;?>
                                    <?php if($user->IsDisabled):?><span class="label">Inactive</span><?php endif;?>
                                </td>
                                <td class="center">
                                    <a class="btn btn-success" href="/admin/users/view/id/<?php echo $user->UserId;?>">
                                        <i class="icon-zoom-in icon-white"></i>
                                        View
                                    </a>
                                    <a class="btn btn-info" href="/admin/users/update/id/<?php echo $user->UserId;?>">
                                        <i class="icon-edit icon-white"></i>
                                        Edit
                                    </a>
                                    <a class="btn btn-danger" href="/admin/users/delete/id/<?php echo $user->UserId;?>" email="<?php echo $user->Email?>">
                                        <i class="icon-trash icon-white"></i>
                                        Delete
                                    </a>
                                </td>
                            </tr>
                          <?php endforeach;?>
                          <?php else:?>
                          <tr><td></td><td></td><td></td><td></td><td></td></tr>
                          <?php endif;?>
                          </tbody>
                      </table>
                    </div>
                </div><!--/span-->

            </div><!--/row-->
