
            <div class="row-fluid">
                <div class="span12">
                        <p>
                            <a href="/admin/users" class="btn btn-medium btn-primary"><i class="icon-chevron-left icon-white"></i> Back to User list</a>
                            <?php if(count($this->User)):?>
                            <a href="/admin/users/update/id/<?php echo $this->User->UserId;?>" class="btn btn-medium btn-info"><i class="icon-edit icon-white"></i> Edit</a>
                            <a href="/admin/users/delete/id/<?php echo $this->User->UserId;?>" class="btn btn-medium btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
                            <?php endif;?>
                        </p>
                </div>
            </div>
            <div class="row-fluid">
                <div class="box span12">
                    <div class="box-header well">
                        <h2><i class="icon-user"></i> View User</h2>
                    </div>
                    <div class="box-content">
                        <?php if(count($this->User)):?>
                        <h1><?php echo $this->User->FirstName;?> <?php echo $this->User->LastName;?></h1>

                        <table>
                        <tr><td class="td-left-customize-view"><b>Email: </b></td><td class="td-right-customize-view"><?php echo $this->User->Email;?></td></tr>
                        <tr><td class="td-left-customize-view"><b>Date Created: </b></td><td class="td-right-customize-view"><?php
                        $createdDate = new Zend_Date($this->User->CreatedDate,DATE_FORMAT_DATABASE);echo $createdDate->toString(DATE_FORMAT_FULL);?>
                        </td></tr>
                        <tr><td class="td-left-customize-view"><b>Last Login: </b></td><td class="td-right-customize-view"><?php
                           if(!empty($this->User->LastLogin)){
                                $lastLogin = new Zend_Date($this->User->LastLogin,DATE_FORMAT_DATABASE);echo $lastLogin->toString(DATE_FORMAT_FULL);
                           }
                           else echo 'N/A';
                        ?></td></tr>
                        <tr><td class="td-left-customize-view"><b>Status: </b></td><td class="td-right-customize-view">
                             <?php if(!$this->User->IsDisabled):?><span class="label label-success">Active</span><?php endif;?>
                             <?php if($this->User->IsDisabled):?><span class="label">Inactive</span><?php endif;?>
                        </td></tr>
                        <tr><td class="td-left-customize-view"><b>Last Edited: </b></td><td class="td-right-customize-view"><?php
                        $lastUpdated = new Zend_Date($this->User->LastUpdated,DATE_FORMAT_DATABASE);echo $lastUpdated->toString(DATE_FORMAT_FULL);?>
                        </td></tr>
                        <tr><td class="td-left-customize-view"><b>Last Edited By: </b></td><td class="td-right-customize-view"><a
                        href="/admin/users/view/id/<?php echo $this->userUpdate->UserId;?>"><?php
                        $lastUpdateBy = $this->userUpdate->FirstName." ".$this->userUpdate->LastName;echo $lastUpdateBy;
                        ?></a>
                        </td></tr>
                        </table>
                        <div class="clearfix"></div>
                        <?php endif;?>
                    </div>
                </div>
            </div>