<?php

    $arrCategories = $this->common()->getConfigByCategoryCode('group-button-social');

    $likeFaceBookUser = null;$followTwitterUser = null;
    $followLinkedInUser = null;$folowGooglePlusUser = null;

    foreach ($arrCategories as $key=>$arrCategory){
        switch ($arrCategory->ConfigCode){
            case 'account-facebook': {$likeFaceBookUser = $arrCategory->ConfigValue;break;}
            case 'account-linkedin': {$followLinkedInUser = $arrCategory->ConfigValue;break;}
            case 'account-twitter': {$followTwitterUser = $arrCategory->ConfigValue;break;}
            case 'account-google-plus': {$folowGooglePlusUser = $arrCategory->ConfigValue;break;}
        }
    }
?>
<!-- START GROUP SOCIAL MEDIA BUTTONS -->
<div id="group-social-media">

    <div class="featurette social-media-content" <?php if(empty($followLinkedInUser)) echo 'style="display:none;"' ?>>
        <div class="pull-left width-social-link-custom-ie padding-feature-social-media">
            <a href="http://www.linkedin.com/company/<?php $linkedInUser = explode("_", $followLinkedInUser);  echo $linkedInUser[1];?>" target="_blank">
            <img class="featurette-image pull-left featurette-custom-image" src="/images/social-media_01.png"></a>
        </div>
        <h5 class="featurette-heading">
        <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
        <script type="IN/FollowCompany" data-id="<?php echo $linkedInUser[1];?>" data-counter="right"></script></h5>
    </div>
    <div class="clear-both"></div>

    <div class="featurette social-media-content" <?php if(empty($followTwitterUser)) echo 'style="display:none;"' ?>>
        <div class="pull-left width-social-link-custom-ie padding-feature-social-media">
            <a href="https://twitter.com/<?php echo $followTwitterUser;?>" target="_blank">
            <img class="featurette-image pull-left featurette-custom-image" src="/images/social-media_02.png"></a>
        </div>
        <h5 class="featurette-heading" style="line-height: 18px !important">
        <iframe src="https://platform.twitter.com/widgets/follow_button.1352365724.html#_=1352806422163&id=twitter-widget-3&lang=en&preview=true&screen_name=<?php echo $followTwitterUser;?>&show_count=false&show_screen_name=false&size=m"
        frameborder="0" id="iframe-button-follow-twitter" class="iframe-button-follow-twitter"></iframe>

        <div id="c" class="count-o">
        <i></i>
        <u></u>
        <a id="count" class="note" href="https://twitter.com/<?php echo $followTwitterUser;?>" target="_blank">
        <span id="count-followers-twitter"></span></a>
        </div>
        </h5>
    </div>
    <div class="clear-both"></div>

    <div class="featurette social-media-content" <?php if(empty($likeFaceBookUser)) echo 'style="display:none;"' ?>>
        <div class="pull-left width-social-link-custom-ie padding-feature-social-media">
            <a href="http://www.facebook.com/<?php echo $likeFaceBookUser;?>" target="_blank">
            <img class="featurette-image pull-left featurette-custom-image" src="/images/social-media_03.png"></a>
        </div>
        <h5 class="featurette-heading">
        <iframe style="width: 150px !important;" src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2F<?php echo $likeFaceBookUser;?>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=442241455813099&locale=en_US"
        scrolling="no" frameborder="0"  class="iframe-button-like-facebook" allowTransparency="true"></iframe></h5>
    </div>

    <div class="clear-both"></div>
    <?php if(in_array($this->common()->getUserBrowser(), array('chrome','safari'))): ?>
    <p style="clear: both;margin-top:22px"></p>
    <?php endif;?>

    <div class="featurette social-media-content" <?php if(empty($folowGooglePlusUser)) echo 'style="display:none;"' ?>>
        <div class="pull-left width-social-link-custom-ie padding-feature-social-media">
            <a href="https://plus.google.com/<?php $googlePlusUser = explode("_", $folowGooglePlusUser);echo $googlePlusUser[1];?>/posts" target="_blank">
            <img class="featurette-image pull-left featurette-custom-image" src="/images/social-media_04.png"></a>
        </div>

        <h5 class="featurette-heading">
            <!-- Place this tag where you want the +1 button to render. -->
            <div class="g-plusone" data-size="medium" data-annotation="bubble"
            data-href="https://plus.google.com/<?php echo $googlePlusUser[1];?>/posts"></div>

            <!-- Place this tag after the last +1 button tag. -->
            <script type="text/javascript">
              (function() {
                var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                po.src = 'https://apis.google.com/js/plusone.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
              })();
            </script>
        </h5>
    </div>
    <div class="clear-both"></div>

</div>
<!-- END GROUP SOCIAL MEDIA BUTTONS -->

        <script type="text/javascript">!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];
            if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

            $(function() {
                $.ajax({
                    url: 'http://api.twitter.com/1/users/show.json',
                    data: {
                        screen_name: '<?php echo $followTwitterUser;?>'
                    },
                    dataType: 'jsonp',
                    success: function(data) {
                        var strCountFollowers = data.followers_count.toString();
                        var widthCountBox = (strCountFollowers.length * 9)+6;
                        $('#count-followers-twitter').html(data.followers_count);
                        $(".count-o").width(widthCountBox);
                    }
                });
            });
        </script>