<?php
function display($input) {
	if(is_object($input)) {
		$input = (array) $input;
	}
	if(is_array($input)) {
		echo '<dl>';
		foreach($input as $key => $value) {
			echo '<dt>' . $key . '</dt>';
			echo '<dd>';
			if(is_array($value) || is_object($value))
				display($value);
			else 
				echo $value;
			echo '</dd>';
		}
		echo '</dl>';
	}
	else {
		echo $input;
	}
}
//$provider->getName();$provider->getApi()->getPicture();$provider->getApi()->getProfile();
echo "<script>parent.close();</script>";

//if(!empty($this->message))  die(var_dump($this->message));
?>


