<?php
 $modelNews = new Application_Model_News();
 $form =  $this->form;
 //$content = (count($news)? $news->toArray() : '');
?>                 <!--People Sections-->
                    <div id="people-block">
                         <h3> Thông tin cần tìm gia sư</h3>

                        <div class="row-fluid">
                            <div class="span12 people-right-block">
                            	<div class="row-fluid">	
								<?php if(! empty($this->messageStatus) && isset($this->messageStatus)): ?>
        						<?php $messageStatus = explode("/", $this->messageStatus); ?>
								<div class="span12">
								     <div class="alert alert-<?php echo $messageStatus[0];?>">
								        <button class="close" data-dismiss="alert" type="button">X</button>
								        <?php echo $messageStatus[1];?>
								        <?php if(isset($this->messages) && sizeof($this->messages) > 0): ?>
						                    <ul>
						                        <?php foreach ($this->messages as $fieldName => $message) : ?>
						                            <?php if ($this->form->$fieldName) : 
						                            		$msg = $this->form->$fieldName->getLabel();
						                            ?>
						                                <li><?php echo substr($msg, 0, -1).': '.$message; ?></li>
						                            <?php else : ?>
						                                <li><?php echo $message; ?></li>
						                            <?php endif; ?>
						                        <?php endforeach; ?>
						                    </ul>
						                <?php endif; ?>
								    </div>
								</div>
								<?php endif;?>
								</div>	
                                <div class="row-fluid">
                                    <div class="span12">
                                        <form class="form-horizontal" method="post" action="" id="frmContact">
								            <fieldset class="well the-fieldset">
								            	<div class="span6">
									            	<?php echo $form->ContactId;?>
									                <?php echo $form->ContactName;?>
									                <?php echo $form->ContactPhone;?>
									                <?php //echo $form->UserId;?>
									                <?php echo $form->ContactTitle;?>
									                <?php echo $form->ContactContent;?>
									                
									                <div class="form-actions">								                    
									            			<?php  echo $this->renderFormElement($form->Save); ?>
									            			<?php  echo $this->renderFormElement($form->Reset); ?>
									                </div>
								                </div>
								            </fieldset>
								        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>