<?php
/**
 * partial loop of Tutors
 * Tutors
 */
 
    $dataRow       = $this->dataRow;
    
?>
<tr>
    
    <td>
        <?php echo $dataRow->DistrictId;?>
    </td>

    <td>
        <?php echo $dataRow->DistrictName;?>
    </td>
    
    <?php 
    	$checked = '';
    	if(in_array($dataRow->DistrictId, explode(',', $this->cdistricts)))
    		$checked = ' checked="checked"';
    ?>
    <td style="vertical-align: middle">
    	<input type="checkbox" id="<?php echo $dataRow->DistrictId; ?>" value="<?php echo $dataRow->DistrictName; ?>" <?php echo $checked?>>
    </td>
</tr>