<div class="author-news">
        <div class="author-name">
           <a href="/people/index/id/<?php echo $this->staff->StaffId; ?>"><?php echo $this->staff->FirstName; ?> <?php echo $this->staff->LastName; ?></a>
        </div>
    <div class="row-fluid">

        <div class="span8 author-news-info">
            <a href="/people/index/id/<?php echo $this->staff->StaffId; ?>">
                <h4><?php echo $this->staff->FirstName; ?> <?php echo $this->staff->LastName; ?></h4>
            </a>
            <?php echo $this->staff->Quote; ?><br />
            <a href="/people/index/id/<?php echo $this->staff->StaffId; ?>" class="color-a-customize">Full profile</a>

            <?php if ($this->staff->LinkinAddress != '' || $this->staff->TwitterAddress != '') : ?>
            <div class="author-news-social-network">
                <?php if ($this->staff->LinkinAddress != '') : ?>
                    <a href="<?php echo $this->staff->LinkinAddress; ?>" target="_blank">
                        <img src="/images/social-media_linkedIn.png"/></a>
                <?php endif; ?>

                &nbsp;

                <?php if ($this->staff->TwitterAddress != '') : ?>
                    <a href="<?php echo $this->staff->TwitterAddress; ?>" target="_blank">
                        <img src="/images/social-media_02.1.png"/></a>
                <?php endif; ?>
            </div>
            <?php endif; ?>
        </div>
        <div class="span4 author-news-avatar">
            <a href="/people/index/id/<?php echo $this->staff->StaffId; ?>">
                <img src="<?php echo $this->staff->Avatar; ?>" />
            </a>
        </div>
    </div>
</div>