<?php
    $bgColors =  array('blue-menu', 'light-green-menu', 'red-pink-menu',
                       'dark-yellow-menu', 'organe-menu', 'dark-blue-menu');
    $categories = $this->categories;
    $cates = count($categories);
?>
<div class="list-category-news">
    <div class="container">
        <div class="span12 row-fluid">
            <ul class="navigation sf-menu display-menu sf-js-enabled sf-shadow">
                <?php if($cates): $c = 1;?>
                <li class="dark-yellow-menu all"><a href="/news"><span> All</span></a></li>
                <?php
                    foreach($categories as $category):
                        if($c == count($bgColors)) $c = 0;
                ?>
                <li class="<?php echo 'dark-yellow-menu cate-'.$category->term_id?>">
                    <a href="/news/index/cate/<? echo $category->term_id?>">
                        <span> <?php echo $category->name?></span>
                    </a>
                </li>
                <?php $c++;endforeach;else:?>
                <li class="blue-menu all"><a href="/news"><span> All</span></a></li>
                <li class="light-green-menu sub-news"><a href="#"><span> News</span></a></li>
                <li class="red-pink-menu blogs"><a href="#"><span> Blogs</span></a></li>
                <li class="dark-yellow-menu articles"><a href="#"><span> Articles</span></a></li>
                <li class="organe-menu reviews"><a href="#"><span> Reviews</span></a></li>
                <li class="dark-blue-menu case-stadies"><a href="#"><span> Case Studies</span></a></li>
                <?php endif;?>
            </ul>
        </div>
    </div>
</div>