<?php $c = 0; foreach ($this->allNewsData['LastestNews'] as $key => $lastestNews):?>
    <?php if (is_numeric($key)) : ?>
    <div class="row-fluid lastest-block">
        <div class="featurette">
            <?php if(!$c):?>
            <h6 class="small-vertical-seperator first-lastest-news">&nbsp;</h6>
            <?php else:?>
            <div class="small-vertical-seperator">&nbsp;</div>
            <?php endif;?>
            <a href="/news/detail/id/<?php echo $lastestNews['id'].(empty($this->cate)?'':'/cate/'.$this->cate); ?>">
            <div class="pull-left">
                <?php if(isset($lastestNews['image']) &&  count($lastestNews['image'])):?>
                <img class="desc-news" src="<?php echo $lastestNews['image']['thumbnail']?>" alt="<?php echo $lastestNews['image']['thumbnail']?>"/>
                <img class="small-news" src="<?php echo $lastestNews['image']['large']?>" alt="<?php echo $lastestNews['image']['large']?>"/>
                <?php else:?>
                <img class="desc-news" src="http://placehold.it/240x120"/>
                <img class="small-news" src="http://placehold.it/770x385"/>
                <?php endif;?>
            </div>
            <span><?php echo $lastestNews['title']?></span></a>
            <div class="lastest-date desc-news"><?php echo $lastestNews['desc']?></div>
            <div class="lastest-date news-date"><?php echo $lastestNews['date']?></div>
        </div>
    </div>
    <?php endif; ?>
<?php $c++;endforeach;?>
<?php if(count($this->paginator) > 1):?>
<div class="row-fluid">
    <?php echo $this->paginationControl($this->paginator,'Sliding','/news/block/lastest-news-pagination.phtml'); ?>
</div>
<?php endif;?>

<?php if($this->paginator->getCurrentItemCount() == LASTEST_NEWS_ITEMS):?>
<div class="loadmorenews"><div class="read-more-news">Read More News</div></div>
<?php endif;?>